In [1]:
import pandas as pd

In [2]:
DFPROMOTIONTABLE1 = pd.read_excel('Promotion _Table.xlsx')

In [3]:
DFPROMOTIONTABLE1

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NaN,Promotion Table,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Offer table,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
109,NaN,7KW56A,NaN,NaN,NaN,NaN,NaN
110,NaN,X2214B,NaN,NaN,NaN,NaN,NaN
111,NaN,8F8Z3PA,NaN,NaN,NaN,NaN,NaN
112,NaN,77S54PA,NaN,NaN,NaN,NaN,NaN
113,NaN,B3P21A,NaN,NaN,NaN,NaN,NaN

In [4]:
DFPROMOTIONTABLE1.drop_duplicates()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NaN,Promotion Table,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Offer table,NaN,NaN,NaN,NaN,NaN
5,NaN,Category,Q1 (Nov-Jan),Q2 (Feb-Apr),Q3 (May-Jul),Q4 (Aug-Oct),NaN
6,NaN,Supply,10% off ink,$2 off toner,5% off toner,20% off ink,NaN
...,...,...,...,...,...,...,...
109,NaN,7KW56A,NaN,NaN,NaN,NaN,NaN
110,NaN,X2214B,NaN,NaN,NaN,NaN,NaN
111,NaN,8F8Z3PA,NaN,NaN,NaN,NaN,NaN
112,NaN,77S54PA,NaN,NaN,NaN,NaN,NaN
113,NaN,B3P21A,NaN,NaN,NaN,NaN,NaN

In [37]:
DFPROMOTIONTABLE1.head(20)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NaN,Promotion Table,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Offer table,NaN,NaN,NaN,NaN,NaN
5,NaN,Category,Q1 (Nov-Jan),Q2 (Feb-Apr),Q3 (May-Jul),Q4 (Aug-Oct),NaN
6,NaN,Supply,10% off ink,$2 off toner,5% off toner,20% off ink,NaN
7,NaN,Print Hardware,15% off ink jet,Free setup service,2% off scanners,$10 off laser jet,NaN
8,NaN,PC,$10 off laptops,Free accessories,Free accessories,15 % off,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,Promotional SKUs,NaN,NaN,NaN,NaN,NaN
13,NaN,For the SKU Below,NaN,NaN,NaN,NaN,NaN
14,NaN,G0L15B,NaN,NaN,NaN,NaN,NaN
15,NaN,7Y4T6QB,NaN,PL,SKU,Season,Promotion
16,NaN,4K0V8PA,NaN,DELLOX_PC_LAPTOP,CN635A,Q3,2000
17,NaN,385Z7PA,NaN,NaN,NaN,NaN,NaN
18,NaN,T6M05AA,NaN,NaN,NaN,NaN,NaN
19,NaN,C4Q32B,NaN,NaN,NaN,NaN,NaN

In [5]:
PROMOTIONTABLE = pd.read_csv('promotion table.csv')

In [ ]:
PROMOTIONTABLE

                    PL      SKU     session  promotion
0       DELLG0_SUP_INK   G0L15B  Q1 Nov-Jan     990.00
1       DELLG0_SUP_INK   G0L15B  Q2 Feb-Apr       2.00
2       DELLG0_SUP_INK   G0L15B  Q3 May-Jul     495.00
3       DELLG0_SUP_INK   G0L15B  Q4 Aug-Oct    1980.00
4    DELL7Y_PC_Desktop  7Y4T6QB  Q1 Nov-Jan      10.00
..                 ...      ...         ...        ...
395     HP77_PC_Laptop  77S54PA  Q4 Aug-Oct   11614.35
396       HPB3_SUP_INK   B3P21A  Q1 Nov-Jan     686.80
397       HPB3_SUP_INK   B3P21A  Q2 Feb-Apr       2.00
398       HPB3_SUP_INK   B3P21A  Q3 May-Jul     343.40
399       HPB3_SUP_INK   B3P21A  Q4 Aug-Oct    1373.60

[400 rows x 4 columns]

In [7]:
import pandas as pd

PROMOTIONTABLE = pd.read_csv('promotion table.csv')

def get_promotions_by_quarter(target_quarter):

    valid_quarters = ['Q1', 'Q2', 'Q3', 'Q4']
    if target_quarter not in valid_quarters:
        return f"Error: Please choose from {valid_quarters}"

    result_df = PROMOTIONTABLE[PROMOTIONTABLE['session'].str.startswith(target_quarter)].copy()
    
    result_df['Selected_Quarter'] = target_quarter
    
    return result_df

df = get_promotions_by_quarter('Q1')

if isinstance(df, str):
    print(df)
else:
    print("Promotions for Q1:")

    print(df[['SKU', 'PL', 'session', 'promotion']].head(10))

Promotions for Q1:
        SKU                 PL     session  promotion
0    G0L15B     DELLG0_SUP_INK  Q1 Nov-Jan      990.0
4   7Y4T6QB  DELL7Y_PC_Desktop  Q1 Nov-Jan       10.0
8   4K0V8PA       HP4K_SUP_INK  Q1 Nov-Jan      108.0
12  385Z7PA    HP38_PC_Desktop  Q1 Nov-Jan       10.0
16  T6M05AA       HPT6_SUP_INK  Q1 Nov-Jan      247.8
20   C4Q32B     DELLC4_SUP_INK  Q1 Nov-Jan      665.9
24  03V96QB   DELL03_PC_Laptop  Q1 Nov-Jan       10.0
28   509O6B     DELL50_SUP_INK  Q1 Nov-Jan      619.1
32  952X8QB   DELL95_PC_Laptop  Q1 Nov-Jan       10.0
36  R3723BG     DELLR3_SUP_TON  Q1 Nov-Jan     1459.6

In [ ]:
DFSELMAP = pd.read_excel('Seller Mapping Table.xlsx')

In [15]:
DFSELMAP

                  Ssellers_name           homologated_sellers
0                Cocoblu Retail           BJ's Wholesale Club
1      RK World Infocom Pvt Ltd                American Eagle
2    Appario Retail Private Ltd                      Tapestry
3              RetailEZ Pvt Ltd           Wakefern / ShopRite
4                 ETrade Online          Harbor Freight Tools
..                          ...                           ...
898            Hydroshell India  Barnes and Noble Booksellers
899                 KT FASHIONS           J.C. Penney Company
900               Shoplite 0000                      Tapestry
901                 Bestbuybook        Sprouts Farmers Market
902                  Seetabooks                  Advance Auto

[903 rows x 2 columns]

In [12]:
DFSELMAP.isnull().sum()

Ssellers_name          0
homologated_sellers    0
dtype: int64

In [17]:
DFSELMAP.dropna()

                  Ssellers_name           homologated_sellers
0                Cocoblu Retail           BJ's Wholesale Club
1      RK World Infocom Pvt Ltd                American Eagle
2    Appario Retail Private Ltd                      Tapestry
3              RetailEZ Pvt Ltd           Wakefern / ShopRite
4                 ETrade Online          Harbor Freight Tools
..                          ...                           ...
898            Hydroshell India  Barnes and Noble Booksellers
899                 KT FASHIONS           J.C. Penney Company
900               Shoplite 0000                      Tapestry
901                 Bestbuybook        Sprouts Farmers Market
902                  Seetabooks                  Advance Auto

[903 rows x 2 columns]

In [19]:
DFSELMAP.drop_duplicates()

                  Ssellers_name           homologated_sellers
0                Cocoblu Retail           BJ's Wholesale Club
1      RK World Infocom Pvt Ltd                American Eagle
2    Appario Retail Private Ltd                      Tapestry
3              RetailEZ Pvt Ltd           Wakefern / ShopRite
4                 ETrade Online          Harbor Freight Tools
..                          ...                           ...
898            Hydroshell India  Barnes and Noble Booksellers
899                 KT FASHIONS           J.C. Penney Company
900               Shoplite 0000                      Tapestry
901                 Bestbuybook        Sprouts Farmers Market
902                  Seetabooks                  Advance Auto

[903 rows x 2 columns]

In [8]:
pip install lxml

Collecting lxml
  Downloading lxml-6.0.2-cp313-cp313-win_amd64.whl.metadata (3.7 kB)
Downloading lxml-6.0.2-cp313-cp313-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   --------------- ------------------------ 1.6/4.0 MB 7.5 MB/s eta 0:00:01
   --------------------------------- ------ 3.4/4.0 MB 8.6 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 7.9 MB/s eta 0:00:00
Installing collected packages: lxml
Successfully installed lxml-6.0.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
DFSKU = pd.read_xml("SKU Table.xml", parser="etree")

In [ ]:
DFSKU

              PN      Sku
0        Pib01a1  0X749QB
1        Pib01a2  75X62BB
2        Pib01a3   DF627B
3        Pib01a4   4ZB96A
4        Pib01a5  0R0N0QB
...          ...      ...
1593  Pib01a1594  4KB93BB
1594  Pib01a1595   X2231B
1595  Pib01a1596   B3P21A
1596  Pib01a1597  78X20QB
1597  Pib01a1598   CF364A

[1598 rows x 2 columns]

In [25]:
DFSKU.dropna()

              PN      Sku
0        Pib01a1  0X749QB
1        Pib01a2  75X62BB
2        Pib01a3   DF627B
3        Pib01a4   4ZB96A
4        Pib01a5  0R0N0QB
...          ...      ...
1593  Pib01a1594  4KB93BB
1594  Pib01a1595   X2231B
1595  Pib01a1596   B3P21A
1596  Pib01a1597  78X20QB
1597  Pib01a1598   CF364A

[1598 rows x 2 columns]

In [26]:
DFSKU.drop_duplicates()

              PN      Sku
0        Pib01a1  0X749QB
1        Pib01a2  75X62BB
2        Pib01a3   DF627B
3        Pib01a4   4ZB96A
4        Pib01a5  0R0N0QB
...          ...      ...
1593  Pib01a1594  4KB93BB
1594  Pib01a1595   X2231B
1595  Pib01a1596   B3P21A
1596  Pib01a1597  78X20QB
1597  Pib01a1598   CF364A

[1598 rows x 2 columns]

In [1]:
import json

In [4]:
PLTABLE = pd.read_json("pl table.json", lines=True)

In [5]:
PLTABLE

          sku                 PL
0     0X749QB   DELL0X_PC_Laptop
1     75X62BB  DELL75_PC_Monitor
2      DF627B     DELLDF_SUP_TON
3      4ZB96A         HP4Z_PH_LJ
4     0R0N0QB   DELL0R_PC_Laptop
...       ...                ...
1593  4KB93BB     DELL4K_SUP_INK
1594   X2231B     DELLX2_SUP_TON
1595   B3P21A       HPB3_SUP_INK
1596  78X20QB  DELL78_PC_Desktop
1597   CF364A       HPCF_SUP_TON

[1598 rows x 2 columns]

In [6]:
PLTABLE["sub_category"] = PLTABLE["PL"].str.split("_", expand=True)[1]

In [7]:
PLTABLE["sub_category"]

0        PC
1        PC
2       SUP
3        PH
4        PC
       ...
1593    SUP
1594    SUP
1595    SUP
1596     PC
1597    SUP
Name: sub_category, Length: 1598, dtype: str

In [8]:
PLTABLE['sub_category'] = PLTABLE['PL'].str.split('_').str[-1]

In [ ]:
PLTABLE

          sku                 PL sub_category
0     0X749QB   DELL0X_PC_Laptop       Laptop
1     75X62BB  DELL75_PC_Monitor      Monitor
2      DF627B     DELLDF_SUP_TON          TON
3      4ZB96A         HP4Z_PH_LJ           LJ
4     0R0N0QB   DELL0R_PC_Laptop       Laptop
...       ...                ...          ...
1593  4KB93BB     DELL4K_SUP_INK          INK
1594   X2231B     DELLX2_SUP_TON          TON
1595   B3P21A       HPB3_SUP_INK          INK
1596  78X20QB  DELL78_PC_Desktop      Desktop
1597   CF364A       HPCF_SUP_TON          TON

[1598 rows x 3 columns]

In [10]:
PLTABLE = pd.read_json("pl table.json", lines=True)   

PLTABLE['sub_category'] = PLTABLE['PL'].str.split('_').str[-1]

PLTABLE

          sku                 PL sub_category
0     0X749QB   DELL0X_PC_Laptop       Laptop
1     75X62BB  DELL75_PC_Monitor      Monitor
2      DF627B     DELLDF_SUP_TON          TON
3      4ZB96A         HP4Z_PH_LJ           LJ
4     0R0N0QB   DELL0R_PC_Laptop       Laptop
...       ...                ...          ...
1593  4KB93BB     DELL4K_SUP_INK          INK
1594   X2231B     DELLX2_SUP_TON          TON
1595   B3P21A       HPB3_SUP_INK          INK
1596  78X20QB  DELL78_PC_Desktop      Desktop
1597   CF364A       HPCF_SUP_TON          TON

[1598 rows x 3 columns]

In [ ]:
Category_Mapping_Table = pd.read_json('Category Mapping Table.json',lines=True)

In [15]:
split_cols = Category_Mapping_Table['PL'].str.split('_')

Category_Mapping_Table['Category'] = split_cols.str.get(1)
Category_Mapping_Table['sub_category'] = split_cols.str.get(2)

In [16]:
Category_Mapping_Table['Category']
Category_Mapping_Table['sub_category']
Category_Mapping_Table

                     PL      sku Category sub_category
0      DELL0X_PC_Laptop  0X749QB       PC       Laptop
1     DELL75_PC_Monitor  75X62BB       PC      Monitor
2        DELLDF_SUP_TON   DF627B      SUP          TON
3            HP4Z_PH_LJ   4ZB96A       PH           LJ
4      DELL0R_PC_Laptop  0R0N0QB       PC       Laptop
...                 ...      ...      ...          ...
1593     DELL4K_SUP_INK  4KB93BB      SUP          INK
1594     DELLX2_SUP_TON   X2231B      SUP          TON
1595       HPB3_SUP_INK   B3P21A      SUP          INK
1596  DELL78_PC_Desktop  78X20QB       PC      Desktop
1597       HPCF_SUP_TON   CF364A      SUP          TON

[1598 rows x 4 columns]

In [63]:
DFCATMAP

                     PL      sku Category sub_category
0      DELL0X_PC_Laptop  0X749QB       PC       Laptop
1     DELL75_PC_Monitor  75X62BB       PC      Monitor
2        DELLDF_SUP_TON   DF627B      SUP          TON
3            HP4Z_PH_LJ   4ZB96A       PH           LJ
4      DELL0R_PC_Laptop  0R0N0QB       PC       Laptop
...                 ...      ...      ...          ...
1593     DELL4K_SUP_INK  4KB93BB      SUP          INK
1594     DELLX2_SUP_TON   X2231B      SUP          TON
1595       HPB3_SUP_INK   B3P21A      SUP          INK
1596  DELL78_PC_Desktop  78X20QB       PC      Desktop
1597       HPCF_SUP_TON   CF364A      SUP          TON

[1598 rows x 4 columns]

In [41]:
DFCATMAP[['Category']]

     Category
0          PC
1          PC
2         SUP
3          PH
4          PC
...       ...
1593      SUP
1594      SUP
1595      SUP
1596       PC
1597      SUP

[1598 rows x 1 columns]

In [ ]:
price_list_table = pd.read_csv('price_list_table.csv')

In [12]:
price_list_table

                    PL      SKU     MAP                LPP
0       DELLG0_SUP_INK   G0L15B    9900     LPP_Q1: 8910.0
1    DELL7Y_PC_Desktop  7Y4T6QB   67545    LPP_Q1: 67535.0
2         HP4K_SUP_INK  4K0V8PA    1080      LPP_Q1: 972.0
3      HP38_PC_Desktop  385Z7PA   50366    LPP_Q1: 50356.0
4         HPT6_SUP_INK  T6M05AA    2478     LPP_Q1: 2230.2
..                 ...      ...     ...                ...
395         HP7K_PH_LJ   7KW56A   58632    LPP_Q4: 58622.0
396     DELLX2_SUP_TON   X2214B    1049      LPP_Q4: 839.2
397     HP8F_PC_Laptop  8F8Z3PA  239399  LPP_Q4: 203489.15
398     HP77_PC_Laptop  77S54PA   77429   LPP_Q4: 65814.65
399       HPB3_SUP_INK   B3P21A    6868     LPP_Q4: 5494.4

[400 rows x 4 columns]

In [ ]:
import pandas as pd
import re

def calculate_lpp(map_price, promo_str):                     
   
    
    if pd.isna(promo_str) or pd.isna(map_price):
        return map_price
    
    promo_str = str(promo_str).strip()
    
    perc_match = re.search(r'(\d+)\s*%', promo_str)
    if perc_match:
        percentage = float(perc_match.group(1)) / 100.0
        return map_price * (1 - percentage)
    
    fixed_match = re.search(r'\$\s*(\d+)', promo_str)
    if fixed_match:
        discount_amount = float(fixed_match.group(1))
        return map_price - discount_amount
    

    if "Free" in promo_str:
        return map_price
    
    return map_price

def run_lpp_process(csv_path, yaml_path):

    df_sku = pd.read_csv(csv_path)


    with open(yaml_path, 'r') as f:
        yaml_content = f.read()
    
    entries = re.findall(r'MAP:\s*(\d+).*?sku:\s*(\w+)', yaml_content, re.DOTALL)
    df_map = pd.DataFrame(entries, columns=['MAP', 'SKU'])
    df_map['MAP'] = df_map['MAP'].astype(float)


    df_final = pd.merge(df_sku, df_map, on='SKU', how='left')


    quarters = ['Q1', 'Q2', 'Q3', 'Q4']
    for q in quarters:
        lpp_column_name = f'LPP_{q}'
        df_final[lpp_column_name] = df_final.apply(
            lambda row: calculate_lpp(row['MAP'], row[q]), axis=1
        )

    return df_final

if __name__ == "__main__":
    results = run_lpp_process('final_100_sku_with_PN.csv', 'Price List Table.yaml')
    
    
    print(results[['SKU', 'MAP', 'Q1', 'LPP_Q1','Q2' ,'LPP_Q2','Q3','LPP_Q3','Q4', 'LPP_Q4']].head(12))
    

    results.to_csv('calculated_lpp_output.csv', index=False)

        SKU       MAP               Q1    LPP_Q1                Q2    LPP_Q2  \
0    G0L15B    9900.0      10% off ink    8910.0      $2 off toner    9898.0
1   7Y4T6QB   67545.0  $10 off laptops   67535.0  Free accessories   67545.0
2   4K0V8PA    1080.0      10% off ink     972.0      $2 off toner    1078.0
3   385Z7PA   50366.0  $10 off laptops   50356.0  Free accessories   50366.0
4   T6M05AA    2478.0      10% off ink    2230.2      $2 off toner    2476.0
5    C4Q32B    6659.0      10% off ink    5993.1      $2 off toner    6657.0
6   03V96QB  123894.0  $10 off laptops  123884.0  Free accessories  123894.0
7    509O6B    6191.0      10% off ink    5571.9      $2 off toner    6189.0
8   952X8QB   39342.0  $10 off laptops   39332.0  Free accessories   39342.0
9   R3723BG   14596.0      10% off ink   13136.4      $2 off toner   14594.0
10  6X4B9PA   60624.0  $10 off laptops   60614.0  Free accessories   60624.0
11  3YM22AA    3939.0      10% off ink    3545.1      $2 off toner    3937.0

                  Q3     LPP_Q3            Q4     LPP_Q4
0       5% off toner    9405.00  20% off  ink    7920.00
1   Free accessories   67545.00      15 % off   57413.25
2       5% off toner    1026.00  20% off  ink     864.00
3   Free accessories   50366.00      15 % off   42811.10
4       5% off toner    2354.10  20% off  ink    1982.40
5       5% off toner    6326.05  20% off  ink    5327.20
6   Free accessories  123894.00      15 % off  105309.90
7       5% off toner    5881.45  20% off  ink    4952.80
8   Free accessories   39342.00      15 % off   33440.70
9       5% off toner   13866.20  20% off  ink   11676.80
10  Free accessories   60624.00      15 % off   51530.40
11      5% off toner    3742.05  20% off  ink    3151.20

In [6]:
!pip install sqlalchemy pandas mysqlclient

Requirement already satisfied: sqlalchemy in c:\users\91950\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: pandas in c:\users\91950\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: mysqlclient in c:\users\91950\anaconda3\lib\site-packages (2.2.8)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\91950\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\91950\anaconda3\lib\site-packages (from sqlalchemy) (4.12.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\91950\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\91950\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\91950\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\91950\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\91950\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [5]:
!pip install pymysql

Requirement already satisfied: pymysql in c:\users\91950\anaconda3\lib\site-packages (1.1.2)

In [4]:
!pip install python-dotenv

Requirement already satisfied: python-dotenv in c:\users\91950\anaconda3\lib\site-packages (1.1.0)

In [13]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
%pip install sqlalchemy pandas pymysql python-dotenv

Requirement already satisfied: sqlalchemy in c:\users\91950\desktop\map\tables\venv\lib\site-packages (2.0.46)
Requirement already satisfied: pandas in c:\users\91950\desktop\map\tables\venv\lib\site-packages (3.0.1)
Requirement already satisfied: pymysql in c:\users\91950\desktop\map\tables\venv\lib\site-packages (1.1.2)
Requirement already satisfied: python-dotenv in c:\users\91950\desktop\map\tables\venv\lib\site-packages (1.2.1)
Requirement already satisfied: greenlet>=1 in c:\users\91950\desktop\map\tables\venv\lib\site-packages (from sqlalchemy) (3.3.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\91950\desktop\map\tables\venv\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\91950\desktop\map\tables\venv\lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\91950\desktop\map\tables\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\91950\desktop\map\tables\venv\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\91950\desktop\map\tables\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [11]:
pip install pymysql

Requirement already satisfied: pymysql in c:\users\91950\desktop\map\tables\venv\lib\site-packages (1.1.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import pandas as pd
import warnings
from sqlalchemy import create_engine
from dotenv import load_dotenv
import os


load_dotenv()

user = os.getenv("DB_USER")
password = os.getenv("DB_PASSWORD")
host = os.getenv("DB_HOST")
port = os.getenv("DB_PORT")
db_name = os.getenv("DB_NAME")


connection_uri = f"mysql+pymysql://{user}:{password}@{host}:{port}/{db_name}"

warnings.filterwarnings('ignore')

try:

    engine = create_engine(connection_uri)
    
    
    PLTABLE = pd.read_json("pl table.json", lines=True) 


    PLTABLE['sub_category'] = PLTABLE['PL'].str.split('_').str[-1]

    PLTABLE

    PLTABLE.to_sql('PLTABLE', engine, index=False, if_exists='replace')
    print("Success: Data uploaded to MySQL!")

except Exception as e:
    print(f"An error occurred: {e}")

finally:

    engine.dispose()

Success: Data uploaded to MySQL!

In [15]:
PLTABLE

          sku                 PL sub_category
0     0X749QB   DELL0X_PC_Laptop       Laptop
1     75X62BB  DELL75_PC_Monitor      Monitor
2      DF627B     DELLDF_SUP_TON          TON
3      4ZB96A         HP4Z_PH_LJ           LJ
4     0R0N0QB   DELL0R_PC_Laptop       Laptop
...       ...                ...          ...
1593  4KB93BB     DELL4K_SUP_INK          INK
1594   X2231B     DELLX2_SUP_TON          TON
1595   B3P21A       HPB3_SUP_INK          INK
1596  78X20QB  DELL78_PC_Desktop      Desktop
1597   CF364A       HPCF_SUP_TON          TON

[1598 rows x 3 columns]

violation letter logic

In [2]:
!pip install python-docx

Collecting python-docx
  Using cached python_docx-1.2.0-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: lxml>=3.1.0 in c:\users\91950\anaconda3\lib\site-packages (from python-docx) (5.3.0)
Requirement already satisfied: typing_extensions>=4.9.0 in c:\users\91950\anaconda3\lib\site-packages (from python-docx) (4.12.2)
Using cached python_docx-1.2.0-py3-none-any.whl (252 kB)
Installing collected packages: python-docx
Successfully installed python-docx-1.2.0

In [ ]:
import pandas as pd
from docx import Document

price_df = pd.read_csv("price_monitoring_table.csv")
violation_df = pd.read_csv("violation_table.csv")

merged_df = pd.merge(price_df, violation_df, left_on="SKU", right_on="sku", how="inner")

merged_df['LPP_numeric'] = merged_df["LPP"].str.extract(r"([\d.]+)").astype(float)
merged_df['Advertised_price'] = pd.to_numeric(merged_df['Advertised_price'], errors='coerce')
merged_df['MAP_Price'] = pd.to_numeric(merged_df['MAP_Price'], errors='coerce')

violations = merged_df[
    (merged_df["Advertised_price"] < merged_df["LPP_numeric"]) |
    (merged_df["Advertised_price"] > merged_df["MAP_Price"])
]

def create_violation_letter(row):
    doc = Document()
    doc.add_heading("Violation Notice", level=1)

    
    content = (
        f"Violation Notice\n"
        f"Seller Name: {row['seller_name']}\n"
        f"Marketplace: {row['Marketplace']}\n"
        f"Category: {row['Category']} - {row['Sub_category']}\n"
        f"Advertised Price: {row['Advertised_price']}\n"
        f"LPP Price: {row['LPP']}\n"
        f"MAP Price: {row['MAP_Price']}\n"
        f"\nThis is to notify you that your advertised price has violated "
        f"the pricing policy. Please ensure compliance with the LPP and MAP guidelines.\n"
        f"{'-'*30}"
    )


    for line in content.split('\n'):
        doc.add_paragraph(line)

    
    filename = f"Violation_{str(row['seller_name']).replace(' ', '_')}_{row['SKU']}.docx"
    doc.save(filename)
    
    return content

print(f"Found {len(violations)} violations. Generating letters...\n")

for _, row in violations.iterrows():
    letter_text = create_violation_letter(row)
    print(letter_text)